<a href="https://colab.research.google.com/github/PRUTU29/ML_LAB/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import pandas as pd

X,y=make_classification(n_samples=10,n_features=4,n_classes=2)
import numpy as np
def kfold_indices(data, k):
    fold_size = len(data) // k
    indices = np.arange(len(data))
    folds = []
    for i in range(k):
        test_indices = indices[i * fold_size: (i + 1) * fold_size]
        train_indices = np.concatenate([indices[:i * fold_size],
indices[(i + 1) * fold_size:]])
        folds.append((train_indices, test_indices))
    return folds

# Define the number of folds (K)
k = 5

# Get the fold indices
fold_indices = kfold_indices(X, k)

from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier  # import ML  model

# Initialize the machine learning model
model = DecisionTreeClassifier()

# Initialize a list to store the evaluation scores
scores = []

# Iterate through each fold
for train_indices, test_indices in fold_indices:
    X_train, y_train = X[train_indices], y[train_indices]
    X_test, y_test = X[test_indices], y[test_indices]

    print('X_train samples')
    print(X_train)
    print('X_test samples')
    print(X_test)
    # Train the model on the training data
    model.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = model.predict(X_test)
    # Calculate the accuracy score for this fold
fold_score = accuracy_score(y_test, y_pred)
# Append the fold score to the list of scores
scores.append(fold_score)
# Calculate the mean accuracy across all folds
mean_accuracy = np.mean(scores)
print("K-Fold Cross-Validation Scores:", scores)
print("Mean Accuracy:", mean_accuracy)

X_train samples
[[-0.61523731  0.11361853  1.39976115 -0.89418436]
 [ 0.99268752  0.63932225 -1.53664264  0.48414786]
 [ 1.02816108  0.75715098 -1.50820655  0.39076646]
 [-0.54427102 -1.0892373   0.19428896  0.59536241]
 [ 0.14272815  1.39665386  0.92397261 -1.45078169]
 [-0.25912627 -1.46913274 -0.74161195  1.39111668]
 [ 0.00876824  1.02913834  0.88454675 -1.18838829]
 [ 0.91154804  2.26438979  0.06081985 -1.50999464]]
X_test samples
[[-0.1198137  -0.95670406 -0.58633467  0.96648501]
 [ 0.25929308 -0.81069748 -1.25930498  1.26575429]]
X_train samples
[[-0.1198137  -0.95670406 -0.58633467  0.96648501]
 [ 0.25929308 -0.81069748 -1.25930498  1.26575429]
 [ 1.02816108  0.75715098 -1.50820655  0.39076646]
 [-0.54427102 -1.0892373   0.19428896  0.59536241]
 [ 0.14272815  1.39665386  0.92397261 -1.45078169]
 [-0.25912627 -1.46913274 -0.74161195  1.39111668]
 [ 0.00876824  1.02913834  0.88454675 -1.18838829]
 [ 0.91154804  2.26438979  0.06081985 -1.50999464]]
X_test samples
[[-0.61523731  0.